# -*- coding: utf-8 -*-
"""elli-project-mainbody.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ1iZAtWj-KaYc35P9ohrtdEaYNI9s1r
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import sklearn
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, confusion_matrix, classification_report
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

"""
This is the cell about tokenization and embedding.
"""

tokenizer = Tokenizer(BPE(unk_token="[UNK]"))

tokenizer.pre_tokenizer = Whitespace()

trainer = BpeTrainer(
    vocab_size=10000,
    special_tokens=["[UNK]", "[PAD]", "[BOS]", "[EOS]", "[CLS]", "[SEP]", "[MASK]"]
)

files = ["wiki.train.raw", "wiki.valid.raw", "wiki.test.raw"]
tokenizer.train(files, trainer)

tokenizer.save("my_custom_tokenizer.json")

loaded_tokenizer = Tokenizer.from_file("my_custom_tokenizer.json")
print(loaded_tokenizer)
loaded_tokenizer.enable_padding(pad_id=1, pad_token="[PAD]")

loaded_tokenizer.enable_truncation(max_length=512)

print("Padding and Truncation have been enabled.")
def encode(target):
  encoded = loaded_tokenizer.encode_batch(target)



# Config
device = "cuda" if torch.cuda.is_available() else raise("GPU not available") break

block_size = 128
batch_size = 64

d_model = 768
n_heads = 12
n_layers = 12
dropout = 0.1

max_steps = 1000
lr = 1.5 e-4
weight_decay = 0.1
grad_clip = 1.0
eval_every = 200
eval_iters = 30

torch.manual_seed(0)

def get_batch(split: str):
    #Change
    d = train_data if split == "train" else val_data
    #Change
    ix = torch.randint(0, len(d) - block_size - 1, (batch_size,))
    x = torch.stack([d[i:i+block_size] for i in ix])
    y = torch.stack([d[i+1:i+block_size+1] for i in ix])
    return x.to(device), y.to(device)

@torch.no_grad()
def estimate_loss(model):
    model.eval()
    out = {}
    #Change
    for split in ["train", "val"]:
        losses = torch.zeros(eval_iters, device=device)
        for k in range(eval_iters):
            xb, yb = get_batch(split)
            _, loss = model(xb, yb)
            losses[k] = loss
        out[split] = losses.mean().item()
    #Change
    model.train()
    return out

# Model
class FeedForward(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.fc1 = nn.Linear(d_model, 4 * d_model)
        self.act = nn.GeLU()
        self.fc2 = nn.Linear(4 * d_model, d_model)
        self.drop = nn.Dropout(dropout)

    def forward(self, x):
        return self.drop(self.fc2(self.act(self.fc1(x))))

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, n_heads, block_size):
        super().__init__()
        assert d_model % n_heads == 0
        self.n_heads = n_heads
        self.head_dim = d_model // n_heads

        self.qkv = nn.Linear(d_model, 3 * d_model, bias=False)
        self.out = nn.Linear(d_model, d_model, bias=False)
        self.drop = nn.Dropout(dropout)

        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, D = x.shape
        H = self.n_heads
        Hd = self.head_dim

        qkv = self.qkv(x)
        q, k, v = qkv.chunk(3, dim=-1)

        q = q.view(B, T, H, Hd).transpose(1, 2)  # (B,H,T,Hd)
        k = k.view(B, T, H, Hd).transpose(1, 2)
        v = v.view(B, T, H, Hd).transpose(1, 2)

        scores = (q @ k.transpose(-2, -1)) / math.sqrt(Hd)  # (B,H,T,T)
        scores = scores.masked_fill(self.tril[:T, :T] == 0, float("-inf"))

        att = F.softmax(scores, dim=-1)
        att = self.drop(att)

        out = att @ v  # (B,H,T,Hd)
        out = out.transpose(1, 2).contiguous().view(B, T, D)
        out = self.drop(self.out(out))
        return out

class TransformerBlock(nn.Module):
    def __init__(self, d_model, n_heads, block_size):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.ln2 = nn.LayerNorm(d_model)
        self.attn = MultiHeadAttention(d_model, n_heads, block_size)
        self.ff = FeedForward(d_model)

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.ff(self.ln2(x))
        return x

class ELLI(nn.Module):
    def __init__(self, vocab_size, d_model, n_heads, n_layers, block_size):
        super().__init__()
        self.block_size = block_size
        self.token_emb = nn.Embedding(vocab_size, d_model)
        self.pos_emb = nn.Embedding(block_size, d_model)
        self.drop = nn.Dropout(dropout)

        self.blocks = nn.ModuleList([
            TransformerBlock(d_model, n_heads, block_size)
            for _ in range(n_layers)
        ])
        self.ln_f = nn.LayerNorm(d_model)
        self.head = nn.Linear(d_model, vocab_size, bias=False)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok = self.token_emb(idx)  # (B,T,D)
        pos = self.pos_emb(torch.arange(T, device=idx.device))  # (T,D)
        x = self.drop(tok + pos)

        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)
        logits = self.head(x)  # (B,T,V)

        loss = None
        if targets is not None:
            loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1))
        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens=200):
        self.eval()
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.block_size:]
            logits, _ = self(idx_cond)
            probs = F.softmax(logits[:, -1, :], dim=-1)
            next_id = torch.multinomial(probs, num_samples=1)
            idx = torch.cat([idx, next_id], dim=1)
        self.train()
        return idx

# Train

model = ELLI(vocab_size, d_model, n_heads, n_layers, block_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

print("device:", device)
print("vocab_size:", vocab_size)
print("params:", sum(p.numel() for p in model.parameters()))

for step in range(max_steps + 1):
    if step % eval_every == 0:
        losses = estimate_loss(model)
        print(f"step {step} | train {losses['train']:.4f} | val {losses['val']:.4f}")

        prompt = "Hello"
        idx = torch.tensor([encode(prompt)], dtype=torch.long, device=device)
        out = model.generate(idx, max_new_tokens=120)
        print(decode(out[0].tolist()))

    xb, yb = get_batch("train")
    _, loss = model(xb, yb)

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()